name: ContinuousIntegration Debug NuGet

on:
  push:
    branches-ignore:
     - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create NuGet Package
      run: dotnet pack -c PackNuGet /p:Version=0.0.0
      working-directory: ./src/
